CREATE TABLE [Cliente]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[PrimeiroNome] VARCHAR(40) NOT NULL,
	[Sobrenome] VARCHAR(40) NOT NULL,
	[Documento] CHAR(11) NOT NULL,
	[Email] VARCHAR(160) NOT NULL,
	[Telefone] VARCHAR(13) NOT NULL
)

CREATE TABLE [Endereco]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[ClienteId] UNIQUEIDENTIFIER NOT NULL,
	[Numero] VARCHAR(10) NOT NULL,
	[Complemento] VARCHAR(40) NOT NULL,
	[Distrito] VARCHAR(60) NOT NULL,
	[Cidade] VARCHAR(60) NOT NULL,
	[Estado] CHAR(2) NOT NULL,
	[Pais] CHAR(2) NOT NULL,
	[Cep] CHAR(8) NOT NULL,
	[Tipo] INT NOT NULL DEFAULT(1),
	FOREIGN KEY ([ClienteId]) REFERENCES [Cliente]([Id])
)

CREATE TABLE [Produto]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[Titulo] VARCHAR(255) NOT NULL,
	[Descricao] TEXT NOT NULL,
	[Imagem] VARCHAR(1024) NOT NULL,
	[Preco] MONEY NOT NULL,
	[QuantidadeEmEstoque] DECIMAL(10, 2) NOT NULL,
)

CREATE TABLE [Pedido]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[ClienteId] UNIQUEIDENTIFIER NOT NULL,
	[DataCriacao] DATETIME NOT NULL DEFAULT(GETDATE()),
	[Status] INT NOT NULL DEFAULT(1),
	FOREIGN KEY([ClienteId]) REFERENCES [Cliente]([Id])
)

CREATE TABLE [ItemPedido] (
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[PedidoId] UNIQUEIDENTIFIER NOT NULL,
	[ProdutoId] UNIQUEIDENTIFIER NOT NULL,
	[Quantidade] DECIMAL(10, 2) NOT NULL,
	[Preco] MONEY NOT NULL,
	FOREIGN KEY([PedidoId]) REFERENCES [Pedido]([Id]),
	FOREIGN KEY([ProdutoId]) REFERENCES [Produto]([Id])
)

CREATE TABLE [Entrega] (
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[PedidoId] UNIQUEIDENTIFIER NOT NULL,
	[DataCriacao] DATETIME NOT NULL DEFAULT(GETDATE()),
	[DataEntregaEstimada]  DATETIME NOT NULL,
	[Status] INT NOT NULL DEFAULT(1),
	FOREIGN KEY([PedidoId]) REFERENCES [Pedido]([Id])
)